apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-monkey
  labels:
    app: kube-monkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-monkey
  template:
    metadata:
      namespace: default
      labels:
        app: kube-monkey
    spec:
      serviceAccountName: kube-monkey
      containers:
      - name: kube-monkey
        image: msvbhat/kube-monkey:12.1
        imagePullPolicy: Always
        env:
        - name: KM_SCHEDULE
          value: "@every 2m"
        - name: DELETE_PERCENTAGE
          value: "50"
        - name: NAMESPACE_WHITELIST
          value: "kube-system"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
