kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-monkey
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-monkey
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-monkey
subjects:
- kind: ServiceAccount
  name: kube-monkey
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: kube-monkey
  apiGroup: ""
